"""initial schema

Revision ID: de3b41aa061d
Revises:
Create Date: 2026-03-06 16:20:27.427362
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de3b41aa061d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legislators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("chamber", sa.String(length=20), nullable=False),
        sa.Column("district", sa.String(length=50), nullable=False),
        sa.Column("party", sa.String(length=50), nullable=False),
        sa.Column("official_website", sa.String(length=500), nullable=True),
        sa.Column("campaign_website", sa.String(length=500), nullable=True),
        sa.Column("facebook_url", sa.String(length=500), nullable=True),
        sa.Column("last_scraped_at", sa.DateTime(), nullable=True),
        sa.Column("scrape_status", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("legislator_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("date", sa.String(length=50), nullable=True),
        sa.Column("time", sa.String(length=50), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=True),
        sa.Column("additional_details", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("is_virtual", sa.Boolean(), nullable=False),
        sa.Column("raw_html_snippet", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["legislator_id"],
            ["legislators.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scrape_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("legislator_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("method_used", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["legislator_id"],
            ["legislators.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scrape_logs")
    op.drop_table("events")
    op.drop_table("legislators")
    # ### end Alembic commands ###
